version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  # - package-ecosystem: "pip"
  #   directory: "/redpepper/manager"
  #   schedule:
  #     interval: "weekly"
  # - package-ecosystem: "pip"
  #   directory: "/redpepper/agent"
  #   schedule:
  #     interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/console"
    schedule:
      interval: "monthly"
