const lightThemes = [
  { id: 'chrome', name: 'Chrome' },
  { id: 'cloud_editor', name: 'CloudEditor' },
  { id: 'clouds', name: 'Clouds' },
  { id: 'cloud9_day', name: 'Cloud9 Day' },
  { id: 'crimson_editor', name: 'Crimson Editor' },
  { id: 'dawn', name: 'Dawn' },
  { id: 'dreamweaver', name: 'Dreamweaver' },
  { id: 'eclipse', name: 'Eclipse' },
  { id: 'github', name: 'GitHub' },
  { id: 'gruvbox_light_hard', name: 'Gruvbox Light Hard' },
  { id: 'iplastic', name: 'IPlastic' },
  { id: 'katzenmilch', name: 'KatzenMilch' },
  { id: 'kuroir', name: 'Kuroir' },
  { id: 'solarized_light', name: 'Solarized Light' },
  { id: 'sqlserver', name: 'SQL Server' },
  { id: 'textmate', name: 'TextMate' },
  { id: 'tomorrow', name: 'Tomorrow' },
  { id: 'xcode', name: 'XCode' }
]

const darkThemes = [
  { id: 'ambiance', name: 'Ambiance' },
  { id: 'chaos', name: 'Chaos' },
  { id: 'cloud_editor_dark', name: 'CloudEditor Dark' },
  { id: 'clouds_midnight', name: 'Clouds Midnight' },
  { id: 'cloud9_night', name: 'Cloud9 Night' },
  { id: 'cloud9_night_low_color', name: 'Cloud9 Night Low-color' },
  { id: 'cobalt', name: 'Cobalt' },
  { id: 'dracula', name: 'Dracula' },
  { id: 'github_dark', name: 'GitHub Dark' },
  { id: 'gob', name: 'Green on Black' },
  { id: 'gruvbox', name: 'Gruvbox' },
  { id: 'gruvbox_dark_hard', name: 'Gruvbox Dark Hard' },
  { id: 'idle_fingers', name: 'Idle Fingers' },
  { id: 'kr_theme', name: 'krTheme' },
  { id: 'merbivore', name: 'Merbivore' },
  { id: 'merbivore_soft', name: 'Merbivore Soft' },
  { id: 'mono_industrial', name: 'Mono Industrial' },
  { id: 'monokai', name: 'Monokai' },
  { id: 'nord_dark', name: 'Nord Dark' },
  { id: 'one_dark', name: 'One Dark' },
  { id: 'pastel_on_dark', name: 'Pastel on Dark' },
  { id: 'solarized_dark', name: 'Solarized Dark' },
  { id: 'terminal', name: 'Terminal' },
  { id: 'tomorrow_night', name: 'Tomorrow Night' },
  { id: 'tomorrow_night_blue', name: 'Tomorrow Night Blue' },
  { id: 'tomorrow_night_bright', name: 'Tomorrow Night Bright' },
  { id: 'tomorrow_night_eighties', name: 'Tomorrow Night 80s' },
  { id: 'twilight', name: 'Twilight' },
  { id: 'vibrant_ink', name: 'Vibrant Ink' }
]
export { darkThemes, lightThemes }
