name: 'Manager and Agent Tests'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.4.26'
          enable-cache: true
          cache-dependency-glob: 'uv.lock'
          prune-cache: ${{ env.ACT != 'true' }}

      - name: Cache UV python installs
        uses: actions/cache@v2
        if: ${{ env.ACT == 'true' }}
        with:
          path: ~/.local/share/uv/python
          key: ${{ runner.os }}-uv-python-${{ hashFiles('.python-version', 'pyproject.toml') }}

      - name: Install dependencies
        run: uv run poe sync

      - name: Run tests
        run: uv run poe test
