name: 'Manager and Agent Tests'

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: ['main']
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: '0.4.26'
          enable-cache: true
          cache-dependency-glob: 'uv.lock'
          prune-cache: ${{ env.ACT != 'true' }}

      - name: Cache UV python installs
        uses: actions/cache@v4
        if: env.ACT == 'true'
        with:
          path: ~/.local/share/uv/python
          key: ${{ runner.os }}-uv-python-${{ hashFiles('.python-version', 'pyproject.toml') }}

      - name: Install dependencies
        run: uv run poe sync

      - name: Run tests with coverage
        run: uv run poe coverage

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v5
        if: env.ACT != 'true'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
